[build]
builder = "nixpacks"
buildCommand = "npm install --prefix backend && npm run build --prefix backend && ./backend/node_modules/.bin/prisma generate --schema=backend/prisma/schema.prisma"

[deploy]
startCommand = "./backend/node_modules/.bin/prisma db push --schema=backend/prisma/schema.prisma --accept-data-loss && node backend/dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
